language: csharp

dist: trusty
sudo: false
mono: none
dotnet: 3.1.100

os:
- linux
#- osx

addons:
  apt:
    #sources:
    #- deadsnakes

    packages:
    - python3.5
    - python3-pip

cache:
  directories:
  - packages/
  - Dependencies/
  - Robust.Client.Godot/.mono/assemblies/

#before_install:
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew update && brew upgrade python; fi

before_script:
#- "pyenv versions"
#- "if [ $TRAVIS_OS_NAME = linux ]; then pyenv shell 3.6; fi"
#- "python3.6 -m pip --v"
#- "python3.6 -m pip install --user --upgrade requests"
- "python3.5 -m pip install --user requests"
- "python3.5 RUN_THIS.py --no-prompt"

script:
- "dotnet build RobustToolbox.sln /p:Python=python3.5"
- "dotnet test"

